var occupationList = [
  "Account Executives or Officer",
  "Accountants",
  "Acturials",
  "AGA's",
  "AGM and Other Senior Manager",
  "Agent",
  "Agricultural Raw Material Related Manufacturing",
  "Agricultural Workers",
  "Air Craft Engineers ( Aeronautic / Maintenance )",
  "Air Conditioning / Refrigeration technicians",
  "Air Craft Technicians",
  "Air Hostesses",
  "Air Stewards",
  "Air Ticketing / Ground Handling Officers",
  "Air Traffic Controllers / Ground Traffic Controllers",
  "Air-Conditioning Engineers",
  "Alcoholic Beverage ( Wine Store/ Bar )",
  "Animal Husbandry Workers",
  "Annoucers",
  "Architects",
  "Art Directors",
  "Asbestos Related Workers",
  "Assistant Accountants",
  "Astrologer",
  "Auditors",
  "Ayurvedic Doctors",
  "Attendant",
  "Athletes",
  "Authors",
  "Auto Electrical",
  "Bank Officer",
  "Barbers",
  "Beauticians and Related Workers",
  "Bicycle Repair Man",
  "Biologists",
  "Black Smiths",
  "Boiler Operators",
  "Book Keepers",
  "Bread and Bakery Products Producers",
  "Brick and Pile Makers",
  "Broadcasting Engineers",
  "Broadcasting Station Operators",
  "Brockers and Assessors",
  "Building Contracter",
  "Building Caretakers",
  "Building Cleaners",
  "Bus Conductor",
  "Business",
  "Business Partner",
  "Business Owner",
  "Butcher",
  "Captains",
  "Carpenters and Other Related Workers",
  "Cashiers",
  "Cement and Concrete Products Manufacturers",
  "Chairman",
  "Chief Ministers",
  "Chmical Process Related Workers",
  "Chemists",
  "Chief Exective Officers",
  "Civil Engineers",
  "Clerks",
  "Coaches",
  "Coconut Pluckers",
  "Coordinator",
  "Coputer Operator",
  "Copywriter",
  "Commentators",
  "Commercial Travelers and Manufacturers Agents",
  "Commisioners of Departments",
  "Communication Agencies and Related Services",
  "Communication Engineers",
  "Construction Meterial Suppliers",
  "Construction Supervisors",
  "Controllers",
  "Cooks / Chefs",
  "Councilller",
  "Court Officials",
  "Crickter",
  "Crane Operator",
  "Creative Diirectors",
  "Custom Security Guards",
  "Cushion Work",
  "Custom Officer",
  "Dairy Manufacturing",
  "Dancers",
  "Dasa Sill Matha",
  "Dental Surgeons",
  "Department Assistant",
  "Deputy Ministers",
  "Deputy / Assistant General Managers",
  "Detectives",
  "Developers",
  "Director Generals",
  "Directors",
  "Divers",
  "Doctors and Surgeons",
  "Domestic Electricians",
  "Draftsman",
  "Dress Makers",
  "Dry Cleaners and Pressing",
  "Driving Instructor",
  "Dyers and Related Workers",
  "Editors",
  "Electrician",
  "Electrical Engineers",
  "Electrical Fitters and Related Electronic Workers",
  "Electical Items / Electronic Manufacturing",
  "Electrical Supply Industry Workers",
  "Engineer",
  "Estate Laborers / Tea Pluckers",
  "Estate Superintendents",
  "Executives and Officere in all Categories",
  "Farmer",
  "Farm Owners and Dairy Producers",
  "Fashion /  Dress Designers",
  "Fashion Parlors ( Saloon/Haif Dressing/Bridal )",
  "Field Officer",
  "Filling Station Pumper  ( E.G Petrol, Gas )",
  "Film, Tele Drama Directors",
  "Finance Manager",
  "Fire Fighters",
  "Fisherman ( Deep Sea )",
  "Fisherman  ( Inland / Coastal )",
  "Foreman",
  "Food ( Excuding Frozen ) Beverage Producers",
  "Food and Bererage Processors",
  "Forces With Special Duties",
  "Forensic Scientists",
  "Forest Officers",
  "Forestry Officers",
  "Forestry Workers",
  "Frozen Food Manufacturing",
  "Furniture Makers and Related Wood Makers",
  "Furniture Munufacturing",
  "Gas Cook Repairing",
  "GA's",
  "Gas Supply Industry Workers",
  "Genarel Foreman ",
  "General Managers",
  "Customer Relationship Officer / Executive",
  "Genetic Scientists",
  "Glass and Glass Products Manufacturers",
  "Glass Formers",
  "Goldsmith",
  "Government Attorneys",
  "Govt.and Privata Institutions",
  "Graphic Designer",
  "Grama Niladari",
  "Gym Instructor",
  "Hair Dressers",
  "Heavy Vehicle Drivers",
  "Homeopathy Doctors",
  "Housemaids and House Keeping Service Workers",
  "Housewives",
  "Insurance Assistant",
  "insurance Salesmen",
  "insurance Advisor",
  "Insurance Financial Manager",
  "Interior Decoration and rRelated Manufacturing",
  "Interior Designers",
  "It Consultants",
  "Jewellery and Precious Metal Workers",
  "Jewellery Designers",
  "Jewellery Selling",
  "Journalists",
  "Juki Machine Operator",
  "Judges",
  "Knitters",
  "Lab Assistant",
  "Lab Officers",
  "Lab Technicians",
  "Labour Tribunal Officials",
  "Labourers",
  "Labourers High Risk Engaging",
  "Landscape Designers",
  "Launders",
  "Laundry",
  "Lawyers",
  "Lecturers in Technica Calleges",
  "Legal and Audit",
  "Legal Officers ( In Private Companies )",
  "Librarian",
  "Life Guard - Coastal",
  "Life Guard - Hotel",
  "Life Guard - Lakes",
  "Life Guard - Rivers",
  "Light Vehichle Drivers",
  "Nurees",
  "Machine Operators",
  "Machine Tool Operators",
  "Machinery Assemblers",
  "Machinery Fitters",
  "Magistrates",
  "Manager",
  "Managers ( Admin/HR/Finance/Sales/Marketing )",
  "Manager (Any other Risk Related )",
  "Managing Director",
  "Manufacturers ( Tea/Rubber and Coconut )",
  "Marine Engineers ",
  "Marine Engineers  Chief",
  "Marine Engineers 2nd",
  "Marine Engineers 3rd",
  "Marine Technicians",
  "Masons",
  "Mathematicians",
  "Mayor",
  "Mechanic - Heavy Vehicles",
  "Mechanic - Light Vehicles",
  "Mechanical Engineers",
  "Media Cnsultants",
  "Media Planners",
  "Medical Attendants",
  "Medica Scientists",
  "Members of Air Force",
  "Members of Army",
  "Members of Home Guard Unit",
  "Members of Navy",
  "Merchandiser",
  "Merchant Navy Officer",
  "Metal Processors",
  "Midwife",
  "Miners",
  "Ministers",
  "Ministry Secretaries",
  "MIS Managers",
  "Monks / Buddust Priests",
  "Municipal Council Workers",
  "Municipal Council Members",
  "Municipal Council Officers",
  "Musicians",
  "Non Residential Worker",
  "Nuns",
  "Other Central Government Officials",
  "Other Electricians",
  "Other Income Source ( Money Londers )",
  "Other Munufacturing Activities ( Chemicals / Plastics )",
  "Other Laboratory Technicians",
  "Paint Artist",
  "Painters - Building Painters",
  "Paper Makers",
  "Parliament Members",
  "Pensioners",
  "Peons and Other Related Workers",
  "Petrol Filling Station Attendants",
  "Pharmaceutical Producers",
  "Pharmacist",
  "Photographer",
  "Physiotherapist",
  "Physical Scientists",
  "Pilot - Major Airline",
  "Pilot",
  "Pilot Other",
  "Plastic Industry Workers",
  "Plumber",
  "Police Service Personnel",
  "Politician",
  "Post  Master",
  "Postmen",
  "Poultry Producers",
  "Pradeshiya Chairman",
  "Pradeshiya Saba Officers",
  "Precision Instrument Makers",
  "Priests ( Catholic / Hindu and Muslim )",
  "Principals",
  "Printing Related Workers",
  "Prison Guards and Jailers",
  "Proprietor",
  "Producers",
  "Production Supervisors",
  "Professional Athletes or Sportsmen",
  "Professional Authors",
  "Professional's Engaged in Dangerous Sports",
  "Programmers",
  "Provincial Council Ministers",
  "Provincial Coucil Officers",
  "Provincial Secretaries",
  "Quality Conttroller",
  "Quarry Workers",
  "Railway Engine Drivers and Guards",
  "Railway Workers",
  "Receptionist",
  "Recovery Officer",
  "Referees",
  "Regional Correspondents",
  "Room Atendant",
  "Road Construction and Maintenance Workers",
  "Rubber Tapers ",
  "Samurdhi Officer",
  "Sand Disintermant",
  "Sales Rep",
  "Sales Represetative",
  "Sailors and Boatsmen",
  "Scientists",
  "Sculptors",
  "Self Employer",
  "Seaman",
  "Secretary ",
  "Secretary ( Political Related )",
  "Secrity Guards / Security Service Workers",
  "Security Guard  ( Using Weapon )",
  "Security Guards ( Without Weapon )",
  "Sewer",
  "Sheet Metal and Structural Metal Preparers and Erectors",
  "Shop Assistants",
  "Singers",
  "Sisters",
  "Software Engineers",
  "Sound Equipment Operatos",
  "Sports Dangerous ",
  "Spinners",
  "State Counsels",
  "Station Masters",
  "Statisticians",
  "Stenographers",
  "Stone Cutters and Carvers",
  "Street Veners and Hawkers",
  "Students",
  "Supervisor",
  "Store Keeper",
  "Supirintandant",
  "Surveyors / Quantity",
  "System Analysts",
  "Tailor",
  "Tax Consultants",
  "Tea Pluckers",
  "Teachers",
  "Technical Salesmen",
  "Technicians",
  "Telegraph Messengers",
  "Telephone Operators and Receptionists",
  "Textile and Garment Manufacturing",
  "Tobacco Producers and Tobacco Product Makers",
  "Toddy Tappers",
  "Tool Makers",
  "Tour Guides ( on Driving )",
  "Toy Makers",
  "Tourist Guide - Driving",
  "Umpires",
  "Uniersity Lecturers",
  "Urban Coucil",
  "Urban Coucil Officers",
  "Vehicle Painters",
  "Veterinary Surgeons",
  "Video Cameramen ",
  "Waiters and Related Workers",
  "Watchers",
  "Weavers",
  "Web Designers",
  "Welders",
  "Well Drillers and Related Workers",
  "Wharf Clerk",
  "Whole Sale and Retail Sale",
  "Wine Stores Owner",
  "Wood Preparation Workers",
  "Zoo Keepers"
];
